# Site settings
title: Piala Mutiara Group - Real Estate Property Developers
email: inf@binwanglobal.com
description: > # this means to ignore newlines until "baseurl:"
  Piala Mutiara Group Sdn. Bhd. (580539-A). Forms parts of Piala Mutiara  Group of companies. Incorporated on 17th May 2002 for the purpose of venturing into activities of civil construction with emphasis to compliment the property development project carried out by Piala Mutiara  Group of companies
baseurl: "/PMG_Demo/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

youtube_username: ""
facebook_username: ""
twitter_username: ""

permalink: /:categories/:title

# Build settings
markdown: kramdown

sass:
  sass_dir: asset/css
  style: :nested
